name: CI/CD Pipeline

on:
  push:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Qt
        uses: riverrun/qt-action@v1
        with:
          qt-version: '5.15.2'  # Update this with your desired Qt version

      - name: Build the project
        run: |
          qmake -project TicTacToe.pro # Replace with your project file name
          make

      - name: Run Tests (if applicable)
        run: ./your_test_executable  # Replace with your test script name (if any)

      - name: Deploy (Optional)
        # Add your deployment steps here based on your chosen deployment method
        # This example showcases a simple artifact upload
        uses: actions/upload-artifact@v3
        with:
          name: tic-tac-toe-built-app

  # Optional job for deployment (uncomment and configure)
  # deploy:
  #   needs: build-and-test
  #   runs-on: ubuntu-latest  # Or your target deployment environment
  #   steps:
  #     - uses: actions/download-artifact@v3
  #       with:
  #         name: tic-tac-toe-built-app
  #
  #     # Add your deployment steps here, leveraging the downloaded artifact
  #     # This example showcases a basic copy
  #     run: cp tic-tac-toe-built-app /deployment/path


