name: Test Workflow

on: push

jobs:
  test:
    name: Test Setup
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '6.7.1'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_msvc2019_64'

      - name: Verify Qt Installation
        run: |
          if not exist C:\Qt\6.7.1\msvc2019_64\bin\qmake.exe (
            echo Qt installation not found!
            exit 1
          ) else (
            echo Qt installation verified.
          )

      - name: Verify qmake version
        run: qmake -v

